<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBvvfden\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBvvfden/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBvvfden.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBvvfden\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBvvfden\appDevDebugProjectContainer();
