<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBctqofu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBctqofu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBctqofu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBctqofu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBctqofu\appDevDebugProjectContainer();
